/**
 * Tests for the Playwright Generator
 */

import { describe, it, expect } from "vitest";
import { generatePlaywright, generateFileName } from "../../generators/playwright-generator.js";
import type { TestSuite, TestCase } from "../../types/ir.js";

const createMockTestSuite = (): TestSuite => ({
  id: "login",
  context: "login",
  sourceFiles: [
    {
      filePath: "src/components/Login.tsx",
      framework: "react",
      language: "tsx",
    },
  ],
  cases: [
    {
      id: "login__happy-path",
      context: "login",
      scenario: "happy-path",
      type: "e2e",
      route: "/login",
      definedAt: [
        {
          filePath: "src/components/Login.tsx",
          line: 56,
          column: 4,
          via: "attribute",
        },
      ],
      steps: [
        {
          id: "step-1",
          action: "type",
          selector: { type: "testId", value: "email" },
          value: "user@example.com",
        },
        {
          id: "step-2",
          action: "type",
          selector: { type: "testId", value: "password" },
          value: "123456",
        },
        {
          id: "step-3",
          action: "click",
          selector: { type: "testId", value: "submit" },
        },
      ],
      expectations: [
        {
          id: "exp-1",
          type: "visible",
          selector: { type: "testId", value: "success-message" },
        },
        {
          id: "exp-2",
          type: "text",
          selector: { type: "testId", value: "success-message" },
          value: "Welcome",
        },
      ],
    },
  ],
});

describe("Playwright Generator", () => {
  describe("generateFileName", () => {
    it("should generate correct file name for test case", () => {
      const testCase: TestCase = {
        id: "login__happy-path",
        context: "login",
        scenario: "happy-path",
        type: "e2e",
        definedAt: [],
        steps: [],
        expectations: [],
      };

      expect(generateFileName(testCase)).toBe("login.happy-path.spec.ts");
    });

    it("should sanitize file names", () => {
      const testCase: TestCase = {
        id: "checkout__invalid user@input",
        context: "checkout",
        scenario: "invalid user@input",
        type: "e2e",
        definedAt: [],
        steps: [],
        expectations: [],
      };

      expect(generateFileName(testCase)).toBe("checkout.invalid-user-input.spec.ts");
    });

    it("should include state in generated file names when present", () => {
      const testCase: TestCase = {
        id: "login__happy-path__success",
        context: "login",
        scenario: "happy-path",
        state: "success",
        type: "e2e",
        definedAt: [],
        steps: [],
        expectations: [],
      };

      expect(generateFileName(testCase)).toBe("login.happy-path.success.spec.ts");
    });
  });

  describe("generatePlaywright", () => {
    it("should generate stable locator helpers", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain('const email = page.locator(\'[data-test-id="email"]\');');
      expect(output).toContain('const password = page.locator(\'[data-test-id="password"]\');');
      expect(output).toContain('const submit = page.locator(\'[data-test-id="submit"]\');');
      expect(output).toContain('const successMessage = page.locator(\'[data-test-id="success-message"]\');');
    });

    it("should include auto-generated header", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain("// Auto-generated by TestWeaver. DO NOT EDIT.");
    });

    it("should include Playwright imports", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain('import { test, expect } from "@playwright/test";');
    });

    it("should generate test.describe block with context name", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain('test.describe("login", () => {');
    });

    it("should generate test cases with scenario names", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain('test("happy-path", async ({ page }) => {');
    });

    it("should include state in the generated test title when present", () => {
      const suite = createMockTestSuite();
      const firstCase = suite.cases[0]!;
      suite.cases[0] = {
        ...firstCase,
        id: "login__happy-path__success",
        state: "success",
      };

      const output = generatePlaywright(suite);

      expect(output).toContain('test("happy-path (success)", async ({ page }) => {');
    });

    it("should navigate to route", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain('await page.goto("/login");');
    });

    it("should generate click step correctly", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain("await submit.click();");
    });

    it("should generate type step (fill) correctly", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain('await email.fill("user@example.com");');
    });

    it("should generate visible expectation correctly", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain("await expect(successMessage).toBeVisible();");
    });

    it("should generate text expectation correctly", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toContain('await expect(successMessage).toContainText("Welcome");');
    });

    it("should match the expected generated output", () => {
      const suite = createMockTestSuite();
      const output = generatePlaywright(suite);

      expect(output).toBe(`// Auto-generated by TestWeaver. DO NOT EDIT.

import { test, expect } from "@playwright/test";

test.describe("login", () => {
  test("happy-path", async ({ page }) => {
    await page.goto("/login");

    const email = page.locator('[data-test-id="email"]');
    const password = page.locator('[data-test-id="password"]');
    const submit = page.locator('[data-test-id="submit"]');
    const successMessage = page.locator('[data-test-id="success-message"]');

    // Steps
    await email.fill("user@example.com");
    await password.fill("123456");
    await submit.click();

    // Expectations
    await expect(successMessage).toBeVisible();
    await expect(successMessage).toContainText("Welcome");
  });

});`);
    });

    it("should produce deterministic output", () => {
      const suite = createMockTestSuite();
      const output1 = generatePlaywright(suite);
      const output2 = generatePlaywright(suite);

      expect(output1).toBe(output2);
    });

    it("should use default route when no route specified", () => {
      const suite: TestSuite = {
        ...createMockTestSuite(),
        cases: [
          {
            id: "login__no-route",
            context: "login",
            scenario: "no-route",
            type: "e2e",
            definedAt: [],
            steps: [],
            expectations: [],
          },
        ],
      };
      const output = generatePlaywright(suite);

      expect(output).toContain('await page.goto("/");');
    });
  });
});
