/**
 * Tests for the Vitest Generator
 */

import { describe, it, expect } from "vitest";
import { generateVitest, generateFileName } from "../../generators/vitest-generator.js";
import type { TestSuite, TestCase } from "../../types/ir.js";

const createMockTestSuite = (): TestSuite => ({
  id: "login",
  context: "login",
  sourceFiles: [
    {
      filePath: "src/components/Login.tsx",
      framework: "react",
      language: "tsx",
    },
  ],
  cases: [
    {
      id: "login__happy-path",
      context: "login",
      scenario: "happy-path",
      type: "ui",
      route: "/login",
      definedAt: [
        {
          filePath: "src/components/Login.tsx",
          line: 56,
          column: 4,
          via: "attribute",
        },
      ],
      steps: [
        {
          id: "step-1",
          action: "type",
          selector: { type: "testId", value: "email" },
          value: "user@example.com",
        },
        {
          id: "step-2",
          action: "type",
          selector: { type: "testId", value: "password" },
          value: "123456",
        },
        {
          id: "step-3",
          action: "click",
          selector: { type: "testId", value: "submit" },
        },
      ],
      expectations: [
        {
          id: "exp-1",
          type: "visible",
          selector: { type: "testId", value: "success-message" },
        },
        {
          id: "exp-2",
          type: "text",
          selector: { type: "testId", value: "success-message" },
          value: "Welcome",
        },
      ],
    },
  ],
});

describe("Vitest Generator", () => {
  describe("generateFileName", () => {
    it("should generate correct file name for test case", () => {
      const testCase: TestCase = {
        id: "login__happy-path",
        context: "login",
        scenario: "happy-path",
        type: "ui",
        definedAt: [],
        steps: [],
        expectations: [],
      };

      expect(generateFileName(testCase)).toBe("login.happy-path.test.tsx");
    });

    it("should sanitize file names", () => {
      const testCase: TestCase = {
        id: "checkout__invalid user@input",
        context: "checkout",
        scenario: "invalid user@input",
        type: "ui",
        definedAt: [],
        steps: [],
        expectations: [],
      };

      expect(generateFileName(testCase)).toBe("checkout.invalid-user-input.test.tsx");
    });
  });

  describe("generateVitest", () => {
    it("should include auto-generated header", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain("// Auto-generated by TestWeaver. DO NOT EDIT.");
    });

    it("should include required imports", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('import { render, screen, fireEvent, waitFor } from "@testing-library/react";');
      expect(output).toContain('import "@testing-library/jest-dom";');
    });

    it("should include component import", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('import { Login } from "src/components/Login.tsx";');
    });

    it("should generate describe block with context name", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('describe("login", () => {');
    });

    it("should generate test cases with scenario names", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('it("happy-path", async () => {');
    });

    it("should render the component", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain("render(<Login />);");
    });

    it("should generate click step correctly", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('fireEvent.click(screen.getByTestId("submit"));');
    });

    it("should generate type step correctly", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('fireEvent.change(screen.getByTestId("email"), { target: { value: "user@example.com" } });');
    });

    it("should generate visible expectation correctly", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('screen.getByTestId("success-message")');
      expect(output).toContain("toBeVisible()");
    });

    it("should generate text expectation correctly", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('toHaveTextContent("Welcome")');
    });

    it("should produce deterministic output", () => {
      const suite = createMockTestSuite();
      const output1 = generateVitest(suite);
      const output2 = generateVitest(suite);

      expect(output1).toBe(output2);
    });
  });
});
