/**
 * Tests for the Vitest Generator
 */

import { describe, it, expect } from "vitest";
import { generateVitest, generateFileName } from "../../generators/vitest-generator.js";
import type { TestSuite, TestCase } from "../../types/ir.js";

const createMockTestSuite = (): TestSuite => ({
  id: "login",
  context: "login",
  sourceFiles: [
    {
      filePath: "src/components/Login.tsx",
      framework: "react",
      language: "tsx",
    },
  ],
  cases: [
    {
      id: "login__happy-path",
      context: "login",
      scenario: "happy-path",
      type: "ui",
      route: "/login",
      definedAt: [
        {
          filePath: "src/components/Login.tsx",
          line: 56,
          column: 4,
          via: "attribute",
        },
      ],
      steps: [
        {
          id: "step-1",
          action: "type",
          selector: { type: "testId", value: "email" },
          value: "user@example.com",
        },
        {
          id: "step-2",
          action: "type",
          selector: { type: "testId", value: "password" },
          value: "123456",
        },
        {
          id: "step-3",
          action: "click",
          selector: { type: "testId", value: "submit" },
        },
      ],
      expectations: [
        {
          id: "exp-1",
          type: "visible",
          selector: { type: "testId", value: "success-message" },
        },
        {
          id: "exp-2",
          type: "text",
          selector: { type: "testId", value: "success-message" },
          value: "Welcome",
        },
      ],
    },
  ],
});

describe("Vitest Generator", () => {
  describe("generateFileName", () => {
    it("should generate correct file name for test case", () => {
      const testCase: TestCase = {
        id: "login__happy-path",
        context: "login",
        scenario: "happy-path",
        type: "ui",
        definedAt: [],
        steps: [],
        expectations: [],
      };

      expect(generateFileName(testCase)).toBe("login.happy-path.test.tsx");
    });

    it("should sanitize file names", () => {
      const testCase: TestCase = {
        id: "checkout__invalid user@input",
        context: "checkout",
        scenario: "invalid user@input",
        type: "ui",
        definedAt: [],
        steps: [],
        expectations: [],
      };

      expect(generateFileName(testCase)).toBe("checkout.invalid-user-input.test.tsx");
    });

    it("should include state in generated file names when present", () => {
      const testCase: TestCase = {
        id: "login__happy-path__success",
        context: "login",
        scenario: "happy-path",
        state: "success",
        type: "ui",
        definedAt: [],
        steps: [],
        expectations: [],
      };

      expect(generateFileName(testCase)).toBe("login.happy-path.success.test.tsx");
    });
  });

  describe("generateVitest", () => {
    it("should generate stable selector helper accessors", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('const email = () => screen.getByTestId("email");');
      expect(output).toContain('const password = () => screen.getByTestId("password");');
      expect(output).toContain('const submit = () => screen.getByTestId("submit");');
      expect(output).toContain('const successMessage = () => screen.getByTestId("success-message");');
    });

    it("should include auto-generated header", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain("// Auto-generated by TestWeaver. DO NOT EDIT.");
    });

    it("should include required imports", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('import { render, screen, fireEvent, waitFor } from "@testing-library/react";');
      expect(output).toContain('import "@testing-library/jest-dom";');
    });

    it("should include component import", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('import { Login } from "src/components/Login.tsx";');
    });

    it("should generate relative component imports when output path is provided", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite, {
        outputFilePath: "/repo/__generated__/vitest/login.happy-path.test.tsx",
        sourceRoot: "/repo",
      });

      expect(output).toContain('import { Login } from "../../src/components/Login.tsx";');
    });

    it("should generate describe block with context name", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('describe("login", () => {');
    });

    it("should generate test cases with scenario names", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('it("happy-path", async () => {');
    });

    it("should include state in the generated test title when present", () => {
      const suite = createMockTestSuite();
      const firstCase = suite.cases[0]!;
      suite.cases[0] = {
        ...firstCase,
        id: "login__happy-path__success",
        state: "success",
      };

      const output = generateVitest(suite);

      expect(output).toContain('it("happy-path (success)", async () => {');
    });

    it("should render the component", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain("render(<Login />);");
    });

    it("should generate click step correctly", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain("fireEvent.click(submit());");
    });

    it("should generate type step correctly", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('fireEvent.change(email(), { target: { value: "user@example.com" } });');
    });

    it("should generate visible expectation correctly", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain("expect(successMessage()).toBeVisible();");
    });

    it("should generate text expectation correctly", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toContain('expect(successMessage()).toHaveTextContent("Welcome");');
    });

    it("should match the expected generated output", () => {
      const suite = createMockTestSuite();
      const output = generateVitest(suite);

      expect(output).toBe(`// Auto-generated by TestWeaver. DO NOT EDIT.

import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import "@testing-library/jest-dom";
import { Login } from "src/components/Login.tsx";

describe("login", () => {
  it("happy-path", async () => {
    render(<Login />);

    const email = () => screen.getByTestId("email");
    const password = () => screen.getByTestId("password");
    const submit = () => screen.getByTestId("submit");
    const successMessage = () => screen.getByTestId("success-message");

    // Steps
    fireEvent.change(email(), { target: { value: "user@example.com" } });
    fireEvent.change(password(), { target: { value: "123456" } });
    fireEvent.click(submit());

    // Expectations
    expect(successMessage()).toBeVisible();
    expect(successMessage()).toHaveTextContent("Welcome");
  });

});`);
    });

    it("should produce deterministic output", () => {
      const suite = createMockTestSuite();
      const output1 = generateVitest(suite);
      const output2 = generateVitest(suite);

      expect(output1).toBe(output2);
    });
  });
});
