/**
 * Tests for the TestWeaver CLI
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

// Paths for testing
const testweaverRoot = path.resolve(__dirname, "../../../");
const fixturesDir = path.resolve(__dirname, "../fixtures");
const testOutputDir = path.resolve(fixturesDir, "__test_generated__");

// CLI path
const cliPath = path.resolve(testweaverRoot, "dist/cli/index.js");

// Create a temporary config file for tests
const testConfigPath = path.resolve(fixturesDir, "testweaver.config.json");
const testConfig = {
  sourceGlobs: ["*.tsx"],
  outputDir: "__test_generated__",
};

describe("CLI", () => {
  beforeAll(() => {
    // Ensure the CLI is built
    if (!fs.existsSync(cliPath)) {
      execSync("npm run build", { cwd: testweaverRoot });
    }
    
    // Clean up any previous test output
    if (fs.existsSync(testOutputDir)) {
      fs.rmSync(testOutputDir, { recursive: true, force: true });
    }

    // Create test config file
    fs.writeFileSync(testConfigPath, JSON.stringify(testConfig, null, 2));
  });

  afterAll(() => {
    // Clean up test output
    if (fs.existsSync(testOutputDir)) {
      fs.rmSync(testOutputDir, { recursive: true, force: true });
    }
    // Clean up test config
    if (fs.existsSync(testConfigPath)) {
      fs.rmSync(testConfigPath);
    }
  });

  describe("generate command", () => {
    it("should display help for generate command", () => {
      const result = execSync(`node ${cliPath} generate --help`, {
        encoding: "utf-8",
      });

      expect(result).toContain("Generate test files from source files");
      expect(result).toContain("-c, --config <path>");
      expect(result).toContain("-o, --output <dir>");
      expect(result).toContain("-w, --watch");
    });

    it("should generate vitest and playwright test files", () => {
      // Run generate command with test config
      const result = execSync(
        `node ${cliPath} generate --config ${testConfigPath}`,
        {
          cwd: fixturesDir,
          encoding: "utf-8",
        }
      );

      // Check output messages
      expect(result).toContain("[INFO] Loading configuration...");
      expect(result).toContain("[INFO] Scanning source files...");
      expect(result).toContain("[INFO] Found 1 source file(s)");

      // Check that vitest directory was created
      const vitestDir = path.join(testOutputDir, "vitest");
      expect(fs.existsSync(vitestDir)).toBe(true);

      // Check that e2e directory was created
      const e2eDir = path.join(testOutputDir, "e2e");
      expect(fs.existsSync(e2eDir)).toBe(true);
    });

    it("should generate files with auto-generated header", () => {
      const vitestDir = path.join(testOutputDir, "vitest");
      const files = fs.readdirSync(vitestDir);
      
      expect(files.length).toBeGreaterThan(0);
      
      const firstFile = path.join(vitestDir, files[0]!);
      const content = fs.readFileSync(firstFile, "utf-8");
      
      expect(content).toContain("// Auto-generated by TestWeaver. DO NOT EDIT.");
    });

    it("should generate vitest files with correct imports", () => {
      const vitestDir = path.join(testOutputDir, "vitest");
      const files = fs.readdirSync(vitestDir);
      const firstFile = path.join(vitestDir, files[0]!);
      const content = fs.readFileSync(firstFile, "utf-8");

      expect(content).toContain("@testing-library/react");
      expect(content).toContain("@testing-library/jest-dom");
      expect(content).toContain("describe(");
      expect(content).toContain("it(");
    });

    it("should generate playwright files with correct imports", () => {
      const e2eDir = path.join(testOutputDir, "e2e");
      const files = fs.readdirSync(e2eDir);
      const firstFile = path.join(e2eDir, files[0]!);
      const content = fs.readFileSync(firstFile, "utf-8");

      expect(content).toContain("@playwright/test");
      expect(content).toContain("test.describe(");
      expect(content).toContain("test(");
      expect(content).toContain("page.goto");
    });

    it("should not overwrite unchanged files", () => {
      const vitestDir = path.join(testOutputDir, "vitest");
      const files = fs.readdirSync(vitestDir);
      const firstFile = path.join(vitestDir, files[0]!);
      
      // Get initial modification time
      const initialStats = fs.statSync(firstFile);
      const initialMtime = initialStats.mtimeMs;
      
      // Wait a bit to ensure time difference
      const waitTime = 100;
      const startTime = Date.now();
      while (Date.now() - startTime < waitTime) {
        // busy wait
      }
      
      // Run generate again
      execSync(`node ${cliPath} generate --config ${testConfigPath}`, {
        cwd: fixturesDir,
        encoding: "utf-8",
      });
      
      // Get new modification time
      const newStats = fs.statSync(firstFile);
      const newMtime = newStats.mtimeMs;
      
      // File should not have been modified (same content)
      expect(newMtime).toBe(initialMtime);
    });
  });

  describe("version and help", () => {
    it("should display version", () => {
      const result = execSync(`node ${cliPath} --version`, {
        encoding: "utf-8",
      });

      expect(result.trim()).toBe("0.1.0");
    });

    it("should display main help", () => {
      const result = execSync(`node ${cliPath} --help`, {
        encoding: "utf-8",
      });

      expect(result).toContain("testweaver");
      expect(result).toContain("generate");
      expect(result).toContain("scan");
      expect(result).toContain("validate");
    });
  });
});
