// Auto-generated by TestWeaver. DO NOT EDIT.

import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import "@testing-library/jest-dom";
import { Login } from "src/components/Login.tsx";

describe("login", () => {
  it("happy-path", async () => {
    render(<Login />);

    // Steps
    fireEvent.change(screen.getByTestId("email"), { target: { value: "user@example.com" } });
    fireEvent.change(screen.getByTestId("password"), { target: { value: "123456" } });
    fireEvent.click(screen.getByTestId("submit"));

    // Expectations
    const el_exp_1 = screen.getByTestId("success-message");
    expect(el_exp_1).toBeVisible();
    const el_exp_2 = screen.getByTestId("success-message");
    expect(el_exp_2).toHaveTextContent("Welcome");
    const el_exp_3 = screen.getByTestId("error-message");
    expect(el_exp_3).toBeVisible();
  });

});