// Auto-generated by TestWeaver. DO NOT EDIT.

import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import "@testing-library/jest-dom";
import { Search } from "src/components/Search.tsx";

describe("search", () => {
  it("happy-path", async () => {
    render(<Search />);

    // Steps
    fireEvent.change(screen.getByTestId("search-input"), { target: { value: "hello" } });
    fireEvent.keyDown(screen.getByTestId("search-input"), { key: "Enter" });
    fireEvent.click(screen.getByTestId("search-submit"));

    // Expectations
    const el_exp_1 = screen.getByTestId("search-results");
    expect(el_exp_1).toBeVisible();
    const el_exp_2 = screen.getByTestId("search-results");
    expect(el_exp_2).toBeInTheDocument();
  });

});