/**
 * Vitest Generator
 *
 * Generates Vitest + React Testing Library test files from IR TestSuite objects.
 */

import * as path from "node:path";

import type {
  TestSuite,
  TestCase,
  TestStep,
  TestExpectation,
  Selector,
} from "../types/ir.js";

interface SelectorBinding {
  readAccessor: string;
  queryAccessor?: string;
}

/**
 * Auto-generated file header comment
 */
const HEADER = "// Auto-generated by TestWeaver. DO NOT EDIT.";

interface GenerateVitestOptions {
  outputFilePath?: string;
  sourceRoot?: string;
}

/**
 * Generates a file name for a test case
 * Format: context.scenario.test.tsx
 */
export function generateFileName(testCase: TestCase): string {
  const context = sanitizeFileName(testCase.context);
  const scenario = sanitizeFileName(testCase.scenario);
  const state = testCase.state !== undefined ? `.${sanitizeFileName(testCase.state)}` : "";
  return `${context}.${scenario}${state}.test.tsx`;
}

function getTestDisplayName(testCase: TestCase): string {
  return testCase.state !== undefined
    ? `${testCase.scenario} (${testCase.state})`
    : testCase.scenario;
}

/**
 * Sanitizes a string for use in a file name
 */
function sanitizeFileName(str: string): string {
  return str.replace(/[^a-zA-Z0-9-_]/g, "-").toLowerCase();
}

/**
 * Escapes a string for use in JavaScript string literals
 */
function escapeString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

/**
 * Escapes a string for use in regex patterns
 */
function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function normalizeImportPath(importPath: string, options: GenerateVitestOptions): string {
  if (options.outputFilePath === undefined) {
    return importPath;
  }

  const sourceRoot = options.sourceRoot ?? process.cwd();
  const absoluteImportPath = path.isAbsolute(importPath)
    ? importPath
    : path.resolve(sourceRoot, importPath);
  const relativeImportPath = path.relative(path.dirname(options.outputFilePath), absoluteImportPath);
  const normalized = relativeImportPath.split(path.sep).join("/");

  if (normalized.startsWith(".")) {
    return normalized;
  }

  return `./${normalized}`;
}

/**
 * Generates a selector expression for React Testing Library
 */
function generateSelector(selector: Selector): string {
  switch (selector.type) {
    case "testId":
      return `screen.getByTestId("${escapeString(selector.value)}")`;
    case "role":
      return `screen.getByRole("${escapeString(selector.value)}")`;
    case "labelText":
      return `screen.getByLabelText("${escapeString(selector.value)}")`;
    case "placeholder":
      return `screen.getByPlaceholderText("${escapeString(selector.value)}")`;
    case "css":
    case "custom":
    default:
      return `document.querySelector("${escapeString(selector.value)}")`;
  }
}

/**
 * Generates a query selector expression for React Testing Library (for not-exists checks)
 */
function generateQuerySelector(selector: Selector): string {
  switch (selector.type) {
    case "testId":
      return `screen.queryByTestId("${escapeString(selector.value)}")`;
    case "role":
      return `screen.queryByRole("${escapeString(selector.value)}")`;
    case "labelText":
      return `screen.queryByLabelText("${escapeString(selector.value)}")`;
    case "placeholder":
      return `screen.queryByPlaceholderText("${escapeString(selector.value)}")`;
    case "css":
    case "custom":
    default:
      return `document.querySelector("${escapeString(selector.value)}")`;
  }
}

/**
 * Converts a selector into a stable key.
 */
function getSelectorKey(selector: Selector): string {
  return `${selector.type}:${selector.value}`;
}

/**
 * Converts text into a safe camelCase identifier.
 */
function toIdentifier(value: string, fallback: string): string {
  const parts = value
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);

  if (parts.length === 0) {
    return fallback;
  }

  const [first, ...rest] = parts;
  const candidate = `${first!.toLowerCase()}${rest
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join("")}`;

  if (/^[0-9]/.test(candidate)) {
    return fallback;
  }

  return candidate;
}

/**
 * Creates stable selector helper bindings for a test case.
 */
function createSelectorBindings(testCase: TestCase): Map<string, SelectorBinding> {
  const bindings = new Map<string, SelectorBinding>();
  const usedNames = new Set<string>();

  const ensureUniqueName = (baseName: string): string => {
    let name = baseName;
    let counter = 2;

    while (usedNames.has(name)) {
      name = `${baseName}${counter}`;
      counter += 1;
    }

    usedNames.add(name);
    return name;
  };

  const registerSelector = (selector: Selector, needsQueryAccessor: boolean): void => {
    const key = getSelectorKey(selector);
    const existing = bindings.get(key);
    if (existing !== undefined) {
      if (needsQueryAccessor && existing.queryAccessor === undefined) {
        existing.queryAccessor = ensureUniqueName(`query${existing.readAccessor.charAt(0).toUpperCase()}${existing.readAccessor.slice(1)}`);
      }
      return;
    }

    const baseName = ensureUniqueName(
      toIdentifier(selector.value, `${selector.type}Element`)
    );
    const binding: SelectorBinding = {
      readAccessor: baseName,
    };

    if (needsQueryAccessor) {
      binding.queryAccessor = ensureUniqueName(
        `query${baseName.charAt(0).toUpperCase()}${baseName.slice(1)}`
      );
    }

    bindings.set(key, binding);
  };

  for (const step of testCase.steps) {
    registerSelector(step.selector, false);
  }

  for (const expectation of testCase.expectations) {
    if (expectation.selector !== undefined) {
      registerSelector(expectation.selector, expectation.type === "not-exists");
    }
  }

  return bindings;
}

/**
 * Generates helper accessors for selectors used in a test case.
 */
function generateSelectorHelperLines(testCase: TestCase, indent: string): string[] {
  const bindings = createSelectorBindings(testCase);
  const lines: string[] = [];

  for (const [key, binding] of bindings) {
    const [selectorType, ...selectorValueParts] = key.split(":");
    const selectorValue = selectorValueParts.join(":");
    const selector = {
      type: selectorType,
      value: selectorValue,
    } as Selector;

    lines.push(`${indent}const ${binding.readAccessor} = () => ${generateSelector(selector)};`);
    if (binding.queryAccessor !== undefined) {
      lines.push(`${indent}const ${binding.queryAccessor} = () => ${generateQuerySelector(selector)};`);
    }
  }

  return lines;
}

/**
 * Generates code for a single test step
 */
function generateStepCode(step: TestStep, binding: SelectorBinding): string {
  const selectorExpr = `${binding.readAccessor}()`;

  switch (step.action) {
    case "click":
      return `fireEvent.click(${selectorExpr});`;
    case "type":
    case "change": {
      const value =
        typeof step.value === "string" ? step.value : String(step.value ?? "");
      return `fireEvent.change(${selectorExpr}, { target: { value: "${escapeString(value)}" } });`;
    }
    case "focus":
      return `fireEvent.focus(${selectorExpr});`;
    case "blur":
      return `fireEvent.blur(${selectorExpr});`;
    case "key": {
      const key =
        typeof step.value === "string" ? step.value : String(step.value ?? "");
      return `fireEvent.keyDown(${selectorExpr}, { key: "${escapeString(key)}" });`;
    }
    case "select": {
      // Select action for dropdown/select elements
      const value =
        typeof step.value === "string" ? step.value : String(step.value ?? "");
      return `fireEvent.change(${selectorExpr}, { target: { value: "${escapeString(value)}" } });`;
    }
    case "hover":
      return `fireEvent.mouseOver(${selectorExpr});`;
    case "clear":
      return `fireEvent.change(${selectorExpr}, { target: { value: "" } });`;
    case "waitFor":
      return `await waitFor(() => expect(${selectorExpr}).toBeInTheDocument());`;
    case "submitContext":
      return `fireEvent.submit(${selectorExpr});`;
    case "custom":
    default:
      return `// Custom step: ${String(step.value ?? step.action)}`;
  }
}

/**
 * Generates code for a single test expectation
 */
function generateExpectationCode(
  expectation: TestExpectation,
  binding?: SelectorBinding
): string {
  if (expectation.selector === undefined) {
    // Handle URL assertions or other selector-less expectations
    switch (expectation.type) {
      case "url-contains":
        return `expect(window.location.href).toContain("${escapeString(String(expectation.value ?? ""))}");`;
      case "url-exact":
        return `expect(window.location.href).toBe("${escapeString(String(expectation.value ?? ""))}");`;
      default:
        return `// Expectation without selector: ${expectation.type}`;
    }
  }

  const selectorExpr = binding !== undefined
    ? `${binding.readAccessor}()`
    : generateSelector(expectation.selector);
  const querySelectorExpr = binding?.queryAccessor !== undefined
    ? `${binding.queryAccessor}()`
    : generateQuerySelector(expectation.selector);

  switch (expectation.type) {
    case "visible":
      return `expect(${selectorExpr}).toBeVisible();`;
    case "not-visible":
      return `expect(${selectorExpr}).not.toBeVisible();`;
    case "exists":
      return `expect(${selectorExpr}).toBeInTheDocument();`;
    case "not-exists":
      return `expect(${querySelectorExpr}).not.toBeInTheDocument();`;
    case "text":
      return `expect(${selectorExpr}).toHaveTextContent("${escapeString(String(expectation.value ?? ""))}");`;
    case "exact-text":
      return `expect(${selectorExpr}).toHaveTextContent(/^${escapeRegex(String(expectation.value ?? ""))}$/);`;
    case "value":
      return `expect(${selectorExpr}).toHaveValue("${escapeString(String(expectation.value ?? ""))}");`;
    case "has-class":
      return `expect(${selectorExpr}).toHaveClass("${escapeString(String(expectation.value ?? ""))}");`;
    case "not-has-class":
      return `expect(${selectorExpr}).not.toHaveClass("${escapeString(String(expectation.value ?? ""))}");`;
    case "aria": {
      // aria expectation value format: "label" or "label:value"
      const ariaValue = String(expectation.value ?? "");
      const colonIndex = ariaValue.indexOf(":");
      if (colonIndex === -1) {
        // Just check for attribute existence
        return `expect(${selectorExpr}).toHaveAttribute("aria-${escapeString(ariaValue)}");`;
      }
      // Check for attribute with specific value
      const ariaName = ariaValue.substring(0, colonIndex);
      const ariaExpectedValue = ariaValue.substring(colonIndex + 1);
      return `expect(${selectorExpr}).toHaveAttribute("aria-${escapeString(ariaName)}", "${escapeString(ariaExpectedValue)}");`;
    }
    case "snapshot":
      return `expect(${selectorExpr}).toMatchSnapshot();`;
    case "custom":
    default:
      return `// Custom expectation: ${expectation.type}`;
  }
}

/**
 * Generates test code for a single TestCase
 */
function generateTestCaseCode(testCase: TestCase, indent: string): string {
  const lines: string[] = [];
  const bindings = createSelectorBindings(testCase);

  // Add steps
  if (testCase.steps.length > 0) {
    lines.push(`${indent}// Steps`);
    for (const step of testCase.steps) {
      const binding = bindings.get(getSelectorKey(step.selector));
      if (binding !== undefined) {
        lines.push(`${indent}${generateStepCode(step, binding)}`);
      }
    }
    lines.push("");
  }

  // Add expectations
  if (testCase.expectations.length > 0) {
    lines.push(`${indent}// Expectations`);
    for (const expectation of testCase.expectations) {
      const binding = expectation.selector !== undefined
        ? bindings.get(getSelectorKey(expectation.selector))
        : undefined;
      lines.push(`${indent}${generateExpectationCode(expectation, binding)}`);
    }
  }

  return lines.join("\n");
}

/**
 * Generates a complete Vitest test file from a TestSuite
 *
 * @param testSuite - The TestSuite to generate tests for
 * @returns The complete test file content as a string
 */
export function generateVitest(testSuite: TestSuite, options: GenerateVitestOptions = {}): string {
  const lines: string[] = [];

  // Add header
  lines.push(HEADER);
  lines.push("");

  // Add imports
  lines.push(
    'import { render, screen, fireEvent, waitFor } from "@testing-library/react";'
  );
  lines.push('import "@testing-library/jest-dom";');

  // Try to determine component import path from sourceFiles or meta
  const sourceFile = testSuite.sourceFiles[0];
  if (sourceFile !== undefined) {
    const componentName =
      testSuite.cases[0]?.meta?.componentName ?? getComponentNameFromPath(sourceFile.filePath);
    const importPath = testSuite.cases[0]?.meta?.importPath ?? sourceFile.filePath;

    if (componentName !== undefined) {
      lines.push(`import { ${componentName} } from "${normalizeImportPath(importPath, options)}";`);
    }
  }

  lines.push("");

  // Generate describe block
  lines.push(`describe("${escapeString(testSuite.context)}", () => {`);

  // Generate test cases
  for (const testCase of testSuite.cases) {
    lines.push(`  it("${escapeString(getTestDisplayName(testCase))}", async () => {`);

    // Render component
    const componentName =
      testCase.meta?.componentName ??
      (sourceFile !== undefined ? getComponentNameFromPath(sourceFile.filePath) : "Component");

    if (componentName !== undefined) {
      lines.push(`    render(<${componentName} />);`);
    }

    lines.push("");

    const selectorHelpers = generateSelectorHelperLines(testCase, "    ");
    if (selectorHelpers.length > 0) {
      lines.push(...selectorHelpers);
      lines.push("");
    }

    // Add test code
    const testCode = generateTestCaseCode(testCase, "    ");
    if (testCode.trim().length > 0) {
      lines.push(testCode);
    }

    lines.push("  });");
    lines.push("");
  }

  lines.push("});");

  return lines.join("\n");
}

/**
 * Extracts a component name from a file path
 * E.g., "src/components/Login.tsx" → "Login"
 */
function getComponentNameFromPath(filePath: string): string | undefined {
  const match = filePath.match(/([A-Z][a-zA-Z0-9]*)\.[jt]sx?$/);
  return match?.[1];
}
