// Auto-generated by TestWeaver. DO NOT EDIT.

import { test, expect } from "@playwright/test";

test.describe("login", () => {
  test("happy-path", async ({ page }) => {
    await page.goto("/login");

    // Steps
    await page.locator('[data-test-id="email"]').fill("user@example.com");
    await page.locator('[data-test-id="password"]').fill("123456");
    await page.locator('[data-test-id="submit"]').click();

    // Expectations
    await expect(page.locator('[data-test-id="success-message"]')).toBeVisible();
    await expect(page.locator('[data-test-id="success-message"]')).toContainText("Welcome");
    await expect(page.locator('[data-test-id="error-message"]')).toBeVisible();
  });

});