// Auto-generated by TestWeaver. DO NOT EDIT.

import { test, expect } from "@playwright/test";

test.describe("search", () => {
  test("happy-path", async ({ page }) => {
    await page.goto("/search");

    // Steps
    await page.locator('[data-test-id="search-input"]').fill("hello");
    await page.locator('[data-test-id="search-input"]').press("Enter");
    await page.locator('[data-test-id="search-submit"]').click();

    // Expectations
    await expect(page.locator('[data-test-id="search-results"]')).toBeVisible();
    await expect(page.locator('[data-test-id="search-results"]')).toBeAttached();
  });

});